trigger:
  branches:
    include:
      - master
  tags:
   include:
      - v*

pool:
  vmImage: 'win1803'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'UpdateTaskVersion.ps1'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/DedupeGitReposV0'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DedupeGitRepos.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'